### ISSUE TITLE
fnum progression broken

### ISSUE THREAD

**Issue by jotego** [nukeykt/Nuked-OPM#9]
When inspecting a full fnum table (1024 entries) produced by the OPM_KCToFNum function, I was surprised to find that for KC values that match KC&0xF0 in between 0xC0 and 0xF0 the fnum progression goes completely out of order and transforms into very small figures.

This looks to me like a bug, but I may be completely loosing out something here. These codes seem to be achieved in the presence of phase modulation. Nonetheless, they do look like a very abrupt change from the regular sequence. 

Please look at the attached file. The first column is the KC number in decimal, then in hex, then the output of OPM_KCToFNum and then my expected fnum progression.

[fnum.txt](https://github.com/nukeykt/Nuked-OPM/files/5981976/fnum.txt)

**Comment by nukeykt** [comment]
That's because kcode to fnum table on real chip does not have entries for these kcode values (it contains only 48 entries). kcode calculation code should not pass these invalid kcode values to OPM_KCToFNum unless there's bug in my code.

**Comment by jotego** [comment]
I see. I suppose the code just returns some value and it doesn't matter in real life. For my implementation I calculated the whole table so I had those values too. It's strange how they left some blanks in the frequency range.
